# Generated by Django 5.1.2 on 2024-10-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_task_task_location_userprofile_on_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
