# Generated by Django 5.1.2 on 2024-10-17 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_alter_task_task_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skill',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='task_management.skill'),
        ),
    ]
