# Generated by Django 5.1.2 on 2024-10-17 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_task_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.skill'),
        ),
    ]
