# Generated by Django 5.1.2 on 2024-10-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_alter_task_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remuneration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
