# Generated by Django 5.1.2 on 2024-10-17 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_alter_task_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.skill'),
        ),
    ]
