# Generated by Django 5.1.2 on 2024-10-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_alter_userskill_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='skill',
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.skill'),
        ),
    ]
