# Generated by Django 5.1.2 on 2024-10-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0009_remove_task_skill_alter_userskill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.skill'),
        ),
    ]
