# Generated by Django 5.1.2 on 2024-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0010_task_required_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_location',
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
