# Generated by Django 5.1.2 on 2024-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_remove_task_task_location_alter_task_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
